package:
  name: essspectroscopy

  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

requirements:
  build:
    - setuptools
    - setuptools_scm
  run:
    - python>=3.10

test:
  imports:
    - ess.spectroscopy
  requires:
    - pytest
  source_files:
    - pyproject.toml
    - tests/
  commands:
    # We ignore warnings during release package builds
    - python -m pytest -Wignore tests

build:
  noarch: python
  script:
    - python -m pip install .

about:
  home: https://github.com/scipp/essspectroscopy
  license: BSD-3-Clause
  summary: Spectroscopy data reduction for the European Spallation Source
  description: Spectroscopy data reduction for the European Spallation Source
  dev_url: https://github.com/scipp/essspectroscopy
  doc_url: https://scipp.github.io/essspectroscopy
